'use strict';
const http = require('http');
const port = process.env.PORT || 1337;

http.createServer((req, res) => {
    if (req.url === '/') { // Handle requests to the home page

        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.write('<html>');
        res.write('<head>');
        res.write('<title>Hello Shoot!</title>');
        res.write('<style>');
        res.write('body { display: flex; height: 100vh; background-color: #46C1D2; }');
        res.write('ul { display: flex; list-style: none; }');
        res.write('li { margin: 10px; text-decoration: none; position: relative; border-radius: 40px; border: 2px solid; }');
        res.write('a { margin: 10px; font-size: 12px; letter-spacing: 0.1em; word-spacing: 0.2em; font-family: Verdana; position: relative; }');
        res.write('h1 { position: absolute; top: 50px; left: 50px; }');
        res.write('p {  position: absolute; top: 100px; left: 50px; }');
        res.write('</style>');
        res.write('</head>');
        res.write('<body>');
        res.write('<header>');
        res.write('<ul>');
        res.write('<li><a href="/learn" id="learn-button">Learn Shoot!</a></li>');
        res.write('<li><a href="/login" id="login-button">Login</a></li>');
        res.write('<li><a href="/signup" id="signup-button">Sign up</a></li>');
        res.write('<li><a href="/shoot" id="shoot-button">Shoot!</a></li>');
        res.write('</ul>');
        res.write('</header>');
        res.write('<h1>Hello Welcome To Shoot!</h1>');
        res.write('<p>Welcome Abroad!<br>Login/Sign Up To Start Shooting!</p>');
        res.write('</body>');
        res.write('</html>');
        res.end();
    } else if (req.url === '/login') { // Handle requests to the login page
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.write('<html>');
        res.write('<head>');
        res.write('<title>Login</title>');
        res.write('<style>');
        res.write('body { display: flex; height: 100vh; background-color: #46C1D2; }');
        res.write('table { display: flex; justify-content: center; align-items: center; height: 100vh; }');
        res.write('ul { display: flex; list-style: none; }');
        res.write('li { margin: 10px; text-decoration: none; position: relative; border-radius: 40px; border: 2px solid; }');
        res.write('a { margin: 10px; font-size: 12px; letter-spacing: 0.1em; word-spacing: 0.2em; font-family: Verdana; position: relative; }');
        res.write('h1 { position: absolute; top: 50px; left: 50px; }');
        res.write('#login-form { display: flex; flex-direction: column; }');
        res.write('#login-form input { margin: 10px; }');
        res.write('</style>');
        res.write('</head>');
        res.write('<body>');
        res.write('<header>');
        res.write('<ul>');
        res.write('<li><a href="/" id="home-button">Home</a></li>');
        res.write('<li><a href="/learn" id="learn-button">Learn Shoot!</a></li>');
        res.write('<li><a href="/signup" id="signup-button">Sign up</a></li>');
        res.write('</ul>');
        res.write('</header>');
        res.write('<h1>Login</h1>');
        res.write('<form id="login-form">');
        res.write('<table>');
        res.write('<tr>');
        res.write('<td><label for="username">Username:</label></td>');
        res.write('<td><input type="text" id="username" name="username"></td>');
        res.write('</tr>');
        res.write('<tr>');
        res.write('<td><label for="password">Password:</label></td>');
        res.write('<td><input type="text" id="password" name="password"></td>');
        res.write('</tr>');
        res.write('<tr>');
        res.write('<td>&nbsp;</td>');
        res.write('<td><input type="submit" value="Submit"></td>');
        res.write('</tr>');
        res.write('</table>');
        res.write('</form>');
        res.write('</body>');
        res.write('</html>');
        res.end();
    } else if (req.url === '/learn') { // Handle requests to the learn page
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.write('<html>');
        res.write('<head>');
        res.write('<title>Learn Shoot!</title>');
        res.write('<style>');
        res.write('body { display: flex; height: 100vh; background-color: #46C1D2; }');
        res.write('ul { display: flex; list-style: none; }');
        res.write('li { margin: 10px; text-decoration: none; position: relative; border-radius: 40px; border: 2px solid; }');
        res.write('a { margin: 10px; font-size: 12px; letter-spacing: 0.1em; word-spacing: 0.2em; font-family: Verdana; position: relative; }');
        res.write('h1 { position: absolute; top: 50px; left: 50px; }');
        res.write('p {  position: absolute; top: 100px; left: 50px; }');
        res.write('</style>');
        res.write('</head>');
        res.write('<body>');
        res.write('<header>');
        res.write('<ul>');
        res.write('<li><a href="/" id="home-button">Home</a></li>');
        res.write('<li><a href="/login" id="login-button">Login</a></li>');
        res.write('<li><a href="/signup" id="signup-button">Sign up</a></li>');
        res.write('</ul>');
        res.write('</header>');
        res.write('<h1>Learn Shoot!</h1>');
        res.write('<p> Shoot! is a sarcastic chatbot you can ask any question you want.<br>Ps: Be ready to get the most sarcastic answers you imagine.</p> ');
        res.write('</body>');
        res.write('</html>');
        res.end();
    } else if (req.url === '/signup') { // Handle requests to the signup page
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.write('<html>');
        res.write('<head>');
        res.write('<title>Sign Up</title>');
        res.write('<style>');
        res.write('body { display: flex; height: 100vh; background-color: #46C1D2; }');
        res.write('table { display: flex; justify-content: center; align-items: center; height: 100vh; }');
        res.write('ul { display: flex; list-style: none; }');
        res.write('li { margin: 10px; text-decoration: none; position: relative; border-radius: 40px; border: 2px solid; }');
        res.write('a { margin: 10px; font-size: 12px; letter-spacing: 0.1em; word-spacing: 0.2em; font-family: Verdana; position: relative; }');
        res.write('h1 { position: absolute; top: 50px; left: 50px; }');
        res.write('#signup-form { display: flex; flex-direction: column; align-items: center; }');
        res.write('#signup-form input { margin: 10px; }');
        res.write('</style>');
        res.write('</head>');
        res.write('<body>');
        res.write('<header>');
        res.write('<ul>');
        res.write('<li><a href="/" id="home-button">Home</a></li>');
        res.write('<li><a href="/learn" id="learn-button">Learn Shoot!</a></li>');
        res.write('<li><a href="/login" id="login-button">Login</a></li>');
        res.write('</ul>');
        res.write('</header>');
        res.write('<h1>Sign Up</h1>');
        res.write('<form id="signup-form">');
        res.write('<table>');
        res.write('<tr>');
        res.write('<td><label for="username">Username:</label></td>');
        res.write('<td><input type="username" id="username" name="username"></td>');
        res.write('</tr>');
        res.write('<tr>');
        res.write('<td><label for="email">Email:</label></td>');
        res.write('<td><input type="email" id="email" name="email"></td>');
        res.write('</tr>');
        res.write('<tr>');
        res.write('<td><label for="password">Password:</label></td>');
        res.write('<td><input type="password" id="password" name="password"></td>');
        res.write('</tr>');
        res.write('<tr>');
        res.write('<td><label for="name">Name:</label></td>');
        res.write('<td><input type="text" id="name" name="name"></td>');
        res.write('</tr>');
        res.write('<tr>');
        res.write('<td><label for="surname">Surname:</label></td>');
        res.write('<td><input type="text" id="surname" name="surname"></td>');
        res.write('</tr>');
        res.write('<tr>');
        res.write('<td><label for="phone">Phone:</label></td>');
        res.write('<td><input type="text" id="phone" name="phone"></td>');
        res.write('</tr>');
        res.write('<tr>');
        res.write('<td>&nbsp;</td>');
        res.write('<td><input type="submit" value="Submit"></td>');
        res.write('</tr>');
        res.write('</table>');
        res.write('</form>');
        res.write('</body>');
        res.write('</html>');
        res.end();
    } else if (req.url === '/shoot') { // Handle requests to the shoot page
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.write('<html>');
        res.write('<head>');
        res.write('<title>Shoot!</title>');
        res.write('<style>');
        res.write('body { display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; background-color: #46C1D2; }');
        res.write('.container { display: flex; flex-direction: column; align-items: center; }');
        res.write('#question { font-weight: bold; margin-bottom: 10px; }');
        res.write('#textbox { margin-bottom: 10px; }');
        res.write('#shoot-button { background-color: #FF6464; color: white; padding: 10px 20px; border: none; border-radius: 5px; margin-bottom: 10px; }');
        res.write('#answer { font-weight: bold; margin-top: 20px; }');
        res.write('#answer-textbox { width: 300px; padding: 5px; }');
        res.write('</style>');
        res.write('</head>');
        res.write('<body>');
        res.write('<h1>Shoot!</h1>');
        res.write('<div class="container">');
        res.write('<div id="question">Enter your question:</div>');
        res.write('<input type="text" id="textbox" name="textbox" placeholder="Your question here">');
        res.write('<button id="shoot-button">Shoot!</button>');
        res.write('<div id="answer">Answer to your question is:</div>');
        res.write('<input type="text" id="answer-textbox" name="answer-textbox" readonly>');
        res.write('</div>');
        res.write('</body>');
        res.write('</html>');
        res.end();
    } else if (req.url === '/myPage') { // Handle requests to the myPage
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.write('<html>');
        res.write('<head>');
        res.write('<title>My Page</title>');
        res.write('<style>');
        res.write('body { display: flex; justify-content: center; align-items: center; height: 100vh; background-color: #46C1D2; }');
        res.write('</style>');
        res.write('</head>');
        res.write('<body>');
        res.write('<h1>Welcome to My Page</h1>');
        res.write('<p>Your question: <strong>' + req.body.question + '</strong></p>'); // Display the submitted question
        res.write('<form id="answer-form" action="/shoot" method="POST">'); // Added action and method attributes
        res.write('<label for="answer">Answer:</label>');
        res.write('<input type="text" id="answer" name="answer">');
        res.write('<input type="submit" value="Submit">');
        res.write('</form>');
        res.write('</body>');
        res.write('</html>');
        res.end();
    } else { // Handle all other requests
        res.writeHead(404, { 'Content-Type': 'text/plain' });
        res.write('404 Not Found');
        res.end();
    }
}).listen(port);
